# Generated by Django 4.2.24 on 2025-09-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="author", name="date_of_birth",),
    ]
