# Generated by Django 4.2.24 on 2025-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="priority",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
