# Generated by Django 4.2.24 on 2025-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservation_priority"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="status",),
        migrations.AlterField(
            model_name="reservation",
            name="priority",
            field=models.PositiveIntegerField(),
        ),
    ]
